pipeline:
  name: mygitpipeline
  identifier: mygitpipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: docker build ACR
        identifier: docker_build_ACR
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: test
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: BuildAndPushACR
                  name: BuildAndPushACR_1
                  identifier: BuildAndPushACR_1
                  spec:
                    connectorRef: ACRAZURECONNNECTIVITY
                    repository: mytestreg.azurecr.io/lastversion
                    tags:
                      - latest
          sharedPaths:
            - ""
          caching:
            enabled: false
            paths: []
          buildIntelligence:
            enabled: false
    - stage:
        name: mytest
        identifier: mytest
        description: ""
        type: IACM
        spec:
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: test
              namespace: harness-delegate-ng
              volumes: []
              annotations: {}
              labels: {}
              automountServiceAccountToken: true
              nodeSelector: {}
              containerSecurityContext:
                capabilities:
                  drop: []
                  add: []
              os: Linux
              hostNames: []
          workspace: testgithub
          execution:
            steps:
              - step:
                  type: IACMTerraformPlugin
                  name: init
                  identifier: init
                  timeout: 10m
                  spec:
                    command: init
                    image: mytestreg.azurecr.io/newpackage:new
                    connectorRef: ACRAZURECONNNECTIVITY
              - step:
                  type: IACMTerraformPlugin
                  name: plan
                  identifier: plan
                  timeout: 10m
                  spec:
                    command: plan
                    image: mytestreg.azurecr.io/newpackage:new
                    connectorRef: ACRAZURECONNNECTIVITY
              - step:
                  type: IACMTerraformPlugin
                  name: apply
                  identifier: apply
                  timeout: 10m
                  spec:
                    command: apply
                    image: mytestreg.azurecr.io/newpackage:new
                    connectorRef: ACRAZURECONNNECTIVITY
        tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitHubConnector
        repoName: windows-runner
        build: <+input>
        sparseCheckout: []
