pipeline:
  name: mygitpipeline
  identifier: mygitpipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: mytest
        identifier: mytest
        description: ""
        type: IACM
        spec:
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: test
              namespace: harness-delegate-ng
              volumes: []
              annotations: {}
              labels: {}
              automountServiceAccountToken: true
              nodeSelector: {}
              containerSecurityContext:
                capabilities:
                  drop: []
                  add: []
              os: Linux
              hostNames: []
          workspace: testgithub
          execution:
            steps:
              - step:
                  type: Run
                  name: azcli
                  identifier: azcli
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine
                    shell: Bash
                    command: |-
                      # Update the package list and install prerequisites
                      sudo apt-get update
                      sudo apt-get install -y ca-certificates curl apt-transport-https lsb-release gnupg

                      # Download and install the Microsoft signing key
                      curl -sL https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -

                      # Add the Azure CLI software repository
                      AZ_REPO=$(lsb_release -cs)
                      echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list

                      # Update the package list and install the Azure CLI
                      sudo apt-get update
                      sudo apt-get install -y azure-cli

                      # Verify the installation
                      az --version
              - step:
                  type: IACMTerraformPlugin
                  name: init
                  identifier: init
                  timeout: 10m
                  spec:
                    command: init
              - step:
                  type: IACMTerraformPlugin
                  name: plan
                  identifier: plan
                  timeout: 10m
                  spec:
                    command: plan
              - step:
                  type: IACMTerraformPlugin
                  name: apply
                  identifier: apply
                  timeout: 10m
                  spec:
                    command: apply
        tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitHubConnector
        repoName: terraform
        build: <+input>
        sparseCheckout: []
