pipeline:
  name: mygitpipeline
  identifier: mygitpipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: mytest
        identifier: mytest
        description: ""
        type: IACM
        spec:
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: test
              namespace: harness-delegate-ng
              volumes: []
              annotations: {}
              labels: {}
              automountServiceAccountToken: true
              nodeSelector: {}
              containerSecurityContext:
                capabilities:
                  drop: []
                  add: []
              os: Linux
              hostNames: []
          workspace: testgithub
          execution:
            steps:
              - step:
                  type: Run
                  name: azcli
                  identifier: azcli
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine
                    shell: Powershell
                    command: |-
                      sudo apt-get update
                      sudo apt-get install -y wget apt-transport-https software-properties-common
                      wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
                      sudo dpkg -i packages-microsoft-prod.deb
                      sudo apt-get update
                      # Download the Azure CLI installer
                      Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi

                      # Install the Azure CLI
                      Start-Process msiexec.exe -ArgumentList '/I AzureCLI.msi /quiet' -NoNewWindow -Wait

                      # Verify the installation
                      az --version
              - step:
                  type: IACMTerraformPlugin
                  name: init
                  identifier: init
                  timeout: 10m
                  spec:
                    command: init
              - step:
                  type: IACMTerraformPlugin
                  name: plan
                  identifier: plan
                  timeout: 10m
                  spec:
                    command: plan
              - step:
                  type: IACMTerraformPlugin
                  name: apply
                  identifier: apply
                  timeout: 10m
                  spec:
                    command: apply
        tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitHubConnector
        repoName: terraform
        build: <+input>
        sparseCheckout: []
