pipeline:
  name: TestPipeline
  identifier: TestPipeline
  tags: {}
  template:
    templateRef: org.testtemplate
    versionLabel: "1"
    templateInputs:
      stages:
        - stage:
            identifier: Dev
            type: IACM
            spec:
              infrastructure:
                type: KubernetesDirect
                spec:
                  connectorRef: <+input>
                  namespace: <+input>
              workspace: <+input>
  projectIdentifier: default_project
  orgIdentifier: default
